### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by wangxingkang** [pansyjs/react-admin#146]
## v2.0.0

- [x] 使用walrus相关库  [wangxingkang](https://github.com/wangxingkang)
- [ ] 使用约定式路由  [wangxingkang](https://github.com/wangxingkang)
- [ ] 升级ant-design至V4 [wangxingkang](https://github.com/wangxingkang)
- [x] 升级umi至V3 [wangxingkang](https://github.com/wangxingkang)
- [ ] 抽取布局为单独项目并发布为包  [wangxingkang](https://github.com/wangxingkang)

## v2.1.0

- [ ] 使用UForm
- [ ] 搭建官网

**Comment by wangxingkang** [comment]
有需要提供支持的可以在下面评论，添加到版本计划里面

**Comment by wangxingkang** [comment]
https://github.com/ts-react/ant-design-layout  布局相关代码会提取到这个项目中
